employees_project/employees_app/urls.py
from django.urls import path

from employees_project.employees_app.views import home, department_details, departments_list, not_found, go_to_home

urlpatterns = [
    path('list/', departments_list, name='department list'),
    path('not_found/', not_found, name='not found'),
    path('<id>/', department_details, name='department details'),

]

employees_project/templates_examples/urls.py
from django.urls import path

from employees_project.templates_examples.views import index

urlpatterns = (
    path('', index, name='templates index'),
)

employees_project/urls.py
from django.contrib import admin
from django.urls import path, include

from employees_project.employees_app.views import home, go_to_home

urlpatterns = (
    path('admin/', admin.site.urls),
    path('', home, name='index'),
    path('go_to_home/', go_to_home, name='go to home'),
    path('departments/', include('employees_project.employees_app.urls')),
    path('templates/', include('employees_project.templates_examples.urls')),
)

employees_project/employees_app/models.py
from django.db import models


class AuditEntity(models.Model):
    created_on = models.DateTimeField(
        auto_now_add=True,
    )
    updated_on = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        abstract = True


class Department(AuditEntity):
    name = models.CharField(
        max_length=20,
    )

    def __str__(self):
        return self.name


class Employee(models.Model):
    SOFTWARE_DEVELOPER = 1
    QA_SPECIALIST = 2
    DEV_OPS_SPECIALIST = 3

    SOFTUNI = 'SoftUni'
    GOOGLE = 'Google'
    FACEBOOK = 'Facebook'
    COMPANIES = (SOFTUNI, GOOGLE, FACEBOOK)

    first_name = models.CharField(
        max_length=30,
    )
    last_name = models.CharField(
        max_length=49,
        null=True,
        blank=True,
    )

    egn = models.CharField(
        max_length=10,
        unique=True,
        verbose_name='EGN',
    )

    job_title = models.IntegerField(
        choices=(
            (SOFTWARE_DEVELOPER, 'Software Developer'),
            (QA_SPECIALIST, 'QA Engineer'),
            (DEV_OPS_SPECIALIST, 'DevOps Specialist'),
        ),
    )

    company = models.CharField(
        max_length=max(len(c) for c in COMPANIES),
        choices=((c, c) for c in COMPANIES),
    )
    # One-to-Many
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ('company', 'first_name',)


class User(models.Model):
    email = models.EmailField()

    # One-to-One Relation
    employee = models.OneToOneField(
        Employee,
        on_delete=models.CASCADE,
        primary_key=True,
    )


class Project(models.Model):
    name = models.CharField(
        max_length=30,
    )

    dead_line = models.DateField(
        null=True,
        blank=True,
    )
    # Many-to_Many
    employees = models.ManyToManyField(
        to=Employee
    )

employees_project/employees_app/views.py
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect
from random import randint


# def home(request):
#     html = f'<h1>{request.method}: This is home.</h1>'
#     return HttpResponse(
#         html,
#         # content_type='text/plain',
#         # content_type='application/xml',
#         # content_type='application/json',
#         content_type=None,
#     )
from django.urls import reverse_lazy

from employees_project.employees_app.models import Department, Employee


def home(request):
    print(reverse_lazy('index'))
    print(reverse_lazy('go to home'))
    print(reverse_lazy('department list'))
    print(reverse_lazy('department details', kwargs = {'id': 1},))
    print(reverse_lazy('not found'))
    context = {
        'number': randint(1, 1003),
        'numbers': [randint(1, 1003) for _ in range(4)],
    }
    return render(request, 'index.html', context)


def go_to_home(request):
    return redirect('index',)


def not_found(request):
    return HttpResponseNotFound()
    # raise Http404()


def department_details(request, id):
    return HttpResponse(f'This is departments details {id}.')


def departments_list(request):
    #  create a new department:
    department = Department(name=f'Department {randint(1, 1234)}')
    department.save()
    # or:
    # Department.objects.create(name=f'Department {randint(1, 1234)}')

    context = {
        # 'departments': Department.objects.all(),                      # generate n + 1 queries
        'departments': Department.objects.prefetch_related('employee_set').all(),
        # 'departments': Department.objects.filter(name='Marketing'),
        # 'departments': Department.objects.filter(name__endswith='app'),
        'employees': Employee.objects.all()


    }
    return render(request, 'departments_list.html', context)

employees_project/templates_examples/views.py
from django.http import HttpResponse
from django.shortcuts import render

from employees_project.employees_app.models import Employee, Department


def index(request):
    context = {
        'num_1': 123,
        'num_2': 321,
        'num_3': 200,
        'numbers': [123, 321, 200],
        'title': 'empLOyees liSt',
        'employees': Employee.objects.order_by('first_name', 'department'),
        'departments': [d.name for d in Department.objects.all()],
    }
    return render(request, 'template_examples/index.html', context)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
<ul>
    <li>
        <a href = {% url 'go to home' %}>HOME</a>
    </li>
    <li>
        <a href = {% url 'templates index' %}>TEMPLATES</a>
    </li>

</ul>
{%  block content %}
{% endblock %}
</body>
</html>

templates/departments_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>List of departments</h1>
<ul>
    {% for d in departments %}
        <li>
            {{ d.name }}
            <ul>
                {% for e in d.employee_set.all %}
                    <li>{{ e.first_name }}</li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
<hr>
    {% for e in employees %}
        <li>
            {{ e.first_name }} ({{ e.department.name }})
        </li>
    {% endfor %}
</ul>
</body>
</html>

templates/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<h1>It works!</h1>
<h2> The number is {{ number }}</h2>
<ul>
    {% for number in numbers %}
        <li> Number is {{ number }} </li>
    {% endfor %}
</ul>
{% endblock %}

templates/tags/departments_list.html
<ul>
    {% for department in departments %}
        <li>
            {{ department.name }}
        </li>
    {% endfor %}
</ul>

templates/template_examples/index.html
{% extends 'base/base.html' %}

{% load custom_tag %}
{% load custom_filter %}

{%  block content %}
<h1>No filter: {{ title }}</h1>
<h1>Custom filter: {{ title|capitalize }}</h1>
<div>
    {{ employees }}
</div>
<hr>
<div>
    {{ departments }}
</div>
<hr>
<div>
    {% if num_1 < 200 %}
        {{ num_1 }} is less than 200
    {% elif num_1 > 200 %}
        {{ num_1 }} is greater than 200
    {% else %}
        {{ num_1 }} is 200
    {% endif %}
</div>
<div>
    {% if num_2 < 200 %}
        {{ num_2 }} is less than 200
    {% elif num_2 > 200 %}
        {{ num_2 }} is greater than 200
    {% else %}
        {{ num_2 }} is 200
    {% endif %}
</div>
<div>
    {% if num_3 < 200 %}
        {{ num_3 }} is less than 200
    {% elif num_3 > 200 %}
        {{ num_3 }} is greater than 200
    {% else %}
        {{ num_3 }} is 200
    {% endif %}
</div>
<hr>
{% for number in numbers %}
    <div>
        {{ number }}
    </div>
{% endfor %}
<hr>
{% for number in numbers %}
    <div>
        {% if number < 200 %}
            {{ number }} is less than 200
        {% elif number > 200 %}
            {{ number }} is greater than 200
        {% else %}
            {{ number }} is 200
        {% endif %}
    </div>
{% endfor %}
<hr>
<ul>
    {% for employee in employees %}
        <li>
            {{ employee.first_name }} - {{ employee.department }}
            {{ employee.get_job_title_display }}
        </li>

    {% endfor %}
</ul>
<hr>
{% departments_list %}

{% endblock %}